#!/usr/bin/env bash
# Do not edit by hand; please use build scripts/templates to make changes
docker push cimg/python:3.7
docker push cimg/python:3.7.16
docker push cimg/python:3.7-node
docker push cimg/python:3.7.16-node
docker push cimg/python:3.7-browsers
docker push cimg/python:3.7.16-browsers
docker push cimg/python:3.8
docker push cimg/python:3.8.16
docker push cimg/python:3.8-node
docker push cimg/python:3.8.16-node
docker push cimg/python:3.8-browsers
docker push cimg/python:3.8.16-browsers
docker push cimg/python:3.9
docker push cimg/python:3.9.16
docker push cimg/python:3.9-node
docker push cimg/python:3.9.16-node
docker push cimg/python:3.9-browsers
docker push cimg/python:3.9.16-browsers
docker push cimg/python:3.10
docker push cimg/python:3.10.9
docker push cimg/python:3.10-node
docker push cimg/python:3.10.9-node
docker push cimg/python:3.10-browsers
docker push cimg/python:3.10.9-browsers
docker push cimg/python:3.11
docker push cimg/python:3.11.1
docker push cimg/python:3.11-node
docker push cimg/python:3.11.1-node
docker push cimg/python:3.11-browsers
docker push cimg/python:3.11.1-browsers
