version: 2.1

orbs:
  cimg: circleci/cimg@0.6.4
  slack: circleci/slack@4.13.1

parameters:
  cron:
    type: boolean
    default: false

workflows:
  automated-wf:
    when: << pipeline.parameters.cron >>
    jobs:
      - cimg/update:
          resource-class: medium.gen3
          pre-steps:
            - run: echo 'export PYENV_ROOT=/home/circleci/.pyenv' >> "$BASH_ENV"
            - run: echo 'export PATH=/home/circleci/.pyenv/shims:/home/circleci/.pyenv/bin:$PATH' >> "$BASH_ENV"
            - run: curl -sSL "https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer" | bash
          update-script: pythonFeed.sh
          context:
            - slack-notification-access-token
            - slack-cimg-notifications
            - cpe-image-bot-github-creds
  main-wf:
    when:
      not: << pipeline.parameters.cron >>
    jobs:
      - build_and_deploy:
          name: "Test"
          filters:
            branches:
              ignore:
                - main
          context:
            - slack-notification-access-token
            - slack-cimg-notifications
            - cimg-docker-image-building
          post-steps:
            - slack/notify:
                branch_pattern: main
                event: fail
                mentions: "@images"
                template: basic_fail_1
      - build_and_deploy:
          name: "Deploy"
          filters:
            branches:
              only:
                - main
          context:
            - slack-notification-access-token
            - slack-cimg-notifications
            - cimg-docker-image-building
            - cimg-docker-image-publishing
          post-steps:
            - slack/notify:
                branch_pattern: main
                event: fail
                mentions: "@images"
                template: basic_fail_1

jobs:
  build_and_deploy:
    machine:
      image: ubuntu-2404:current
    resource_class: 2xlarge+.gen3
    steps:
      - run:
          name: Install latest QEMU
          command: sudo apt-get update && sudo apt-get install qemu-system
      - run:
          name: Register binfmt for supported platforms
          command: docker run --privileged --rm tonistiigi/binfmt --install all
      - checkout
      - run:
          name: Docker login
          command: echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin
      - when:
          condition:
            not:
              equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run:
                name: "Build and deploy to ccitest/python"
                command: |
                  DOCKER_NAMESPACE="ccitest"
                  source ./manifest
  
                  while IFS= read -r line; do
  
                  if [[ $arm64 == "1" ]]; then
                    directory=$(echo "$line" | awk '{print $6}')
                  else
                    directory=$(echo "$line" | awk '{print $4}')
                  fi
                  if [[ "${directory}" =~ "Dockerfile" ]]; then
                    if [ "${parent:?}" != "base" ]; then
                      sed -i "s|cimg/${repository:?}|${DOCKER_NAMESPACE}/${repository}|g" "$directory"
                      sed -i "s|cimg/${parent}|${DOCKER_NAMESPACE}/${parent}|g" "$directory"
                    else
                      sed -i "s|cimg/$repository|${DOCKER_NAMESPACE}/${repository}|g" "$directory"
                    fi
                  fi
  
                  done < ./build-images.sh
  
                  sed 's|cimg|'"${DOCKER_NAMESPACE}"'|g' ./build-images.sh > ./build-images-stage.sh
  
                  chmod +x ./build-images-stage.sh
                  ./build-images-stage.sh
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run:
                name: "Build and deploy to cimg/python"
                command: ./build-images.sh
