version: 2.1

orbs:
  cimg: circleci/cimg@0.6.4
  slack: circleci/slack@4.13.1

parameters:
  cron:
    type: boolean
    default: false

workflows:
  automated-wf:
    when: << pipeline.parameters.cron >>
    jobs:
      - cimg/update:
          pre-steps:
            - run: echo 'export PYENV_ROOT=/home/circleci/.pyenv' >> "$BASH_ENV"
            - run: echo 'export PATH=/home/circleci/.pyenv/shims:/home/circleci/.pyenv/bin:$PATH' >> "$BASH_ENV"
            - run: curl -sSL "https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer" | bash

          update-script: pythonFeed.sh
          context:
            - slack-notification-access-token
            - slack-cimg-notifications
            - cpe-image-bot-github-creds
  main-wf:
    when:
      not: << pipeline.parameters.cron >>
    jobs:
      - cimg/build-and-deploy:
          name: "Test"
          resource-class: 2xlarge+
          docker-namespace: ccitest
          docker-repository: python
          filters:
            branches:
              ignore:
                - main
          context:
            - slack-notification-access-token
            - slack-cimg-notifications
            - cimg-docker-image-building
          post-steps:
            - slack/notify:
                branch_pattern: main
                event: fail
                mentions: "@images"
                template: basic_fail_1
      - cimg/build-and-deploy:
          name: "Deploy"
          resource-class: 2xlarge+
          docker-repository: python
          filters:
            branches:
              only:
                - main
          context:
            - slack-notification-access-token
            - slack-cimg-notifications
            - cimg-docker-image-building
            - cimg-docker-image-publishing
          post-steps:
            - slack/notify:
                branch_pattern: main
                event: fail
                mentions: "@images"
                template: basic_fail_1
